# Generated by Django 3.0.5 on 2020-05-17 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memeCoreApp', '0002_meme_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meme',
            name='category',
            field=models.CharField(choices=[('New', 'New'), ('Nerd', 'Nerd'), ('Quotes', 'Quotes'), ('Programming', 'Programming'), ('Daily struggle', 'Daily Struggle')], default='No category chosen', max_length=15),
        ),
    ]
