# Generated by Django 3.0.6 on 2020-06-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeCoreApp', '0006_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='category',
            field=models.CharField(choices=[('Nerd', 'Nerd'), ('Quotes', 'Quotes'), ('Programming', 'Programming'), ('Daily struggle', 'Daily Struggle')], default='No category chosen', max_length=15),
        ),
    ]
