# Generated by Django 3.0.4 on 2020-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_comment',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
