# Generated by Django 3.0.5 on 2020-05-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_comment',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
