# Generated by Django 3.0.5 on 2020-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='category',
            field=models.CharField(choices=[('new', 'New'), ('nerd', 'Nerd'), ('quotes', 'Quotes'), ('programming', 'Programming'), ('daily struggle', 'Daily Struggle')], default='new', max_length=15),
        ),
    ]
