# Generated by Django 3.0.4 on 2020-04-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_auto_20200320_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
