# Generated by Django 3.0.4 on 2020-05-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_auto_20200516_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
        migrations.AddField(
            model_name='like',
            name='meme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.Meme'),
            preserve_default=False,
        ),
    ]
