# Generated by Django 3.0.5 on 2020-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0003_auto_20200517_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
