# Generated by Django 3.0.5 on 2020-04-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0004_auto_20200421_1352'),
        ('myFirstApp', '0004_register'),
    ]

    operations = [
    ]
