# Generated by Django 3.0.5 on 2020-05-06 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0004_memeimage_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='memes')),
            ],
        ),
        migrations.AlterField(
            model_name='memeimage',
            name='meme_Main_Img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='memes'),
        ),
    ]
