# Generated by Django 3.0.5 on 2020-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0005_auto_20200506_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memeimage',
            name='meme_Main_Img',
        ),
        migrations.AddField(
            model_name='memeimage',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='memes/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='memeimage',
            name='imgCaption',
            field=models.CharField(max_length=500),
        ),
    ]
