# Generated by Django 3.0.4 on 2020-05-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0005_auto_20200530_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
