# Generated by Django 3.0.4 on 2020-05-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_auto_20200516_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.AddField(
            model_name='comment',
            name='meme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.Meme'),
        ),
    ]
