# Generated by Django 3.0.5 on 2020-05-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_auto_20200506_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memeimage',
            name='image',
        ),
        migrations.AddField(
            model_name='memeimage',
            name='meme_Main_Img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='memes'),
        ),
        migrations.AlterField(
            model_name='memeimage',
            name='imgCaption',
            field=models.CharField(max_length=200),
        ),
    ]
