# Generated by Django 3.0.5 on 2020-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0007_auto_20200506_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
