# Generated by Django 3.0.4 on 2020-05-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0007_auto_20200516_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.Meme'),
        ),
    ]
