# Generated by Django 3.0.5 on 2020-05-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0008_auto_20200506_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemeImage',
            new_name='Upload',
        ),
    ]
