# Generated by Django 3.0.4 on 2020-05-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0008_auto_20200516_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
