# Generated by Django 3.0.5 on 2020-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0009_auto_20200511_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='imgCaption',
            new_name='Caption',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='meme_Main_Img',
        ),
        migrations.AddField(
            model_name='upload',
            name='Image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
