# Generated by Django 3.0.4 on 2020-05-19 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0009_auto_20200517_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='meme',
            name='category',
            field=models.CharField(choices=[('New', 'New'), ('Nerd', 'Nerd'), ('Quotes', 'Quotes'), ('Programming', 'Programming'), ('Daily struggle', 'Daily Struggle')], default='No category chosen', max_length=15),
        ),
        migrations.AddField(
            model_name='meme',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
