# Generated by Django 3.0.5 on 2020-05-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0010_auto_20200511_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Caption',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media/'),
        ),
    ]
