# Generated by Django 3.0.5 on 2020-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0011_auto_20200512_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='meme_images'),
        ),
    ]
