# Generated by Django 3.0.5 on 2020-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0012_auto_20200512_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
