# Generated by Django 3.0.5 on 2020-05-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0013_auto_20200512_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/meme_images'),
        ),
    ]
