# Generated by Django 3.0.5 on 2020-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0014_meme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/meme_images/'),
        ),
    ]
