# Generated by Django 3.0.5 on 2020-05-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0015_auto_20200512_1601'),
        ('myFirstApp', '0005_merge_20200430_1700'),
    ]

    operations = [
    ]
