# Generated by Django 3.0.4 on 2020-05-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0019_auto_20200513_1151'),
        ('myFirstApp', '0016_merge_20200512_1741'),
    ]

    operations = [
    ]
